name: Build and Deploy Weather App to EC2

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/weather-app .

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/weather-app

    - name: Deploy to EC2 (install Docker + run container)
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Instalar Docker si no est치 instalado
          if ! command -v docker &> /dev/null; then
            echo "Docker no est치 instalado. Instalando..."
            sudo apt update
            sudo apt install -y docker.io
            sudo systemctl enable docker
            sudo usermod -aG docker $USER
          else
            echo "Docker ya est치 instalado."
          fi

          # Descargar la imagen m치s reciente desde Docker Hub
          docker pull ${{ secrets.DOCKER_USERNAME }}/weather-app

          # Detener y eliminar contenedor previo si existe
          docker stop weather-app || true
          docker rm weather-app || true

          # Ejecutar nuevo contenedor
          docker run -d -p 80:80 --name weather-app ${{ secrets.DOCKER_USERNAME }}/weather-app
